/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IrrCalculatorRouteImport } from './routes/irr-calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareCaseIdRouteImport } from './routes/compare.$caseId'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrCalculatorRoute = IrrCalculatorRouteImport.update({
  id: '/irr-calculator',
  path: '/irr-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCaseIdRoute = CompareCaseIdRouteImport.update({
  id: '/compare/$caseId',
  path: '/compare/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/irr-calculator': typeof IrrCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/compare/$caseId': typeof CompareCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/irr-calculator': typeof IrrCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/compare/$caseId': typeof CompareCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/irr-calculator': typeof IrrCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/compare/$caseId': typeof CompareCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/irr-calculator'
    | '/sitemap.xml'
    | '/case/$caseId'
    | '/compare/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/irr-calculator'
    | '/sitemap.xml'
    | '/case/$caseId'
    | '/compare/$caseId'
  id:
    | '__root__'
    | '/'
    | '/irr-calculator'
    | '/sitemap.xml'
    | '/case/$caseId'
    | '/compare/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IrrCalculatorRoute: typeof IrrCalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
  CompareCaseIdRoute: typeof CompareCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irr-calculator': {
      id: '/irr-calculator'
      path: '/irr-calculator'
      fullPath: '/irr-calculator'
      preLoaderRoute: typeof IrrCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$caseId': {
      id: '/compare/$caseId'
      path: '/compare/$caseId'
      fullPath: '/compare/$caseId'
      preLoaderRoute: typeof CompareCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IrrCalculatorRoute: IrrCalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
  CompareCaseIdRoute: CompareCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
